### ISSUE TITLE
Tweak keeps asking for update in cydia

### ISSUE THREAD

**Issue by one2gov** [EthanRDoesMC/EthanRDoesMC.github.io#2] opened 2017-02-06 11:18 UTC

**Comment by EthanRDoesMC** [comment] 2017-02-08 02:53
Confirmed. I have absolutely no idea (so far) how to fix it, but I have it too.

**Comment by EthanRDoesMC** [comment] 2017-02-09 02:26
Should be fixed.

**Comment by EthanRDoesMC** [comment] 2017-02-09 15:14
Seems to be back. UGH! I'm going to (try to) make a 10.1.1 version of Gandalf, so I'll see if I can fix this once and for all!

**Comment by EthanRDoesMC** [comment] 2017-02-14 14:55
Should be fixed by the end of the day.

**Comment by EthanRDoesMC** [comment] 2017-03-18 15:24
Fixed.

**Closed by EthanRDoesMC** 2017-03-18 15:24 UTC
